import { Plaque } from "./plaques";
import { BusinessUser } from "./users";

export interface SaleRecord {
  id: string;
  plaqueId: string;
  plaqueName: string;
  sellerId: string;
  sellerName: string;
  buyerId: string;
  buyerName: string;
  saleDate: string; // ISO date string
  salePrice: number;
  commissionAmount: number;
  payoutStatus: "Pending" | "Paid" | "Cancelled";
  status: "Completed" | "Canceled";
}

export const mockSaleRecords: SaleRecord[] = [
  {
    id: "sale-001",
    plaqueId: "plaque-001",
    plaqueName: "Golden Anniversary Plaque",
    sellerId: "biz-001",
    sellerName: "The Gourmet Place",
    buyerId: "biz-002",
    buyerName: "Chic Boutique",
    saleDate: "2023-10-26T10:00:00Z",
    salePrice: 1500,
    commissionAmount: 150,
    payoutStatus: "Paid",
    status: "Completed",
  },
  {
    id: "sale-002",
    plaqueId: "plaque-003",
    plaqueName: "Diamond Jubilee Plaque",
    sellerId: "biz-002",
    sellerName: "Chic Boutique",
    buyerId: "biz-001",
    buyerName: "The Gourmet Place",
    saleDate: "2023-11-15T11:30:00Z",
    salePrice: 2000,
    commissionAmount: 200,
    payoutStatus: "Pending",
    status: "Completed",
  },
  {
    id: "sale-003",
    plaqueId: "plaque-005",
    plaqueName: "Platinum Achievement Plaque",
    sellerId: "biz-001",
    sellerName: "The Gourmet Place",
    buyerId: "biz-003",
    buyerName: "Wellness Wonders",
    saleDate: "2023-12-01T14:00:00Z",
    salePrice: 1200,
    commissionAmount: 120,
    payoutStatus: "Pending",
    status: "Completed",
  },
  {
    id: "sale-004",
    plaqueId: "plaque-002",
    plaqueName: "Silver Recognition Plaque",
    sellerId: "biz-002",
    sellerName: "Chic Boutique",
    buyerId: "biz-001",
    buyerName: "The Gourmet Place",
    saleDate: "2024-01-05T09:00:00Z",
    salePrice: 800,
    commissionAmount: 80,
    payoutStatus: "Paid",
    status: "Completed",
  },
  {
    id: "sale-005",
    plaqueId: "plaque-004",
    plaqueName: "Bronze Merit Plaque",
    sellerId: "biz-003",
    sellerName: "Wellness Wonders",
    buyerId: "biz-002",
    buyerName: "Chic Boutique",
    saleDate: "2024-02-10T16:00:00Z",
    salePrice: 500,
    commissionAmount: 50,
    payoutStatus: "Pending",
    status: "Completed",
  },
  {
    id: "sale-006",
    plaqueId: "plaque-006",
    plaqueName: "Community Hero Plaque",
    sellerId: "biz-001",
    sellerName: "The Gourmet Place",
    buyerId: "biz-004",
    buyerName: "Startup Solutions",
    saleDate: "2024-03-20T10:00:00Z",
    salePrice: 1000,
    commissionAmount: 100,
    payoutStatus: "Paid",
    status: "Completed",
  },
  {
    id: "sale-007",
    plaqueId: "plaque-007",
    plaqueName: "Innovation Award Plaque",
    sellerId: "biz-002",
    sellerName: "Chic Boutique",
    buyerId: "biz-003",
    buyerName: "Wellness Wonders",
    saleDate: "2024-04-01T13:00:00Z",
    salePrice: 1800,
    commissionAmount: 180,
    payoutStatus: "Pending",
    status: "Completed",
  },
  {
    id: "sale-008",
    plaqueId: "plaque-008",
    plaqueName: "Leadership Recognition Plaque",
    sellerId: "biz-003",
    sellerName: "Wellness Wonders",
    buyerId: "biz-004",
    buyerName: "Startup Solutions",
    saleDate: "2024-05-05T15:00:00Z",
    salePrice: 1300,
    commissionAmount: 130,
    payoutStatus: "Pending",
    status: "Completed",
  },
  {
    id: "sale-009",
    plaqueId: "plaque-009",
    plaqueName: "Excellence in Service Plaque",
    sellerId: "biz-001",
    sellerName: "The Gourmet Place",
    buyerId: "biz-002",
    buyerName: "Chic Boutique",
    saleDate: "2024-06-12T09:00:00Z",
    salePrice: 950,
    commissionAmount: 95,
    payoutStatus: "Paid",
    status: "Completed",
  },
  {
    id: "sale-010",
    plaqueId: "plaque-010",
    plaqueName: "Teamwork Achievement Plaque",
    sellerId: "biz-002",
    sellerName: "Chic Boutique",
    buyerId: "biz-001",
    buyerName: "The Gourmet Place",
    saleDate: "2024-07-22T10:00:00Z",
    salePrice: 1100,
    commissionAmount: 110,
    payoutStatus: "Pending",
    status: "Completed",
  },
];
