export enum CashbackEvent {
  // Loyalty Events
  MEMBERSHIP_PURCHASE = "MEMBERSHIP_PURCHASE",
  WALLET_TOPUP = "WALLET_TOPUP",
  POINT_PACKAGE_PURCHASE = "POINT_PACKAGE_PURCHASE",
  STAMP_PACKAGE_PURCHASE = "STAMP_PACKAGE_PURCHASE",

  // Mall Events (Included for consistency, though primarily used in Mall)
  ORDER_PAYMENT = "ORDER_PAYMENT",
  SERVICE_BOOKING_PAYMENT = "SERVICE_BOOKING_PAYMENT",
  GIFT_CARD_PURCHASE = "GIFT_CARD_PURCHASE",
  VOUCHER_PURCHASE = "VOUCHER_PURCHASE",
  GROUP_CONTRIBUTION_PAYMENT = "GROUP_CONTRIBUTION_PAYMENT",
  MALL_MEMBERSHIP_PAYMENT = 'MALL_MEMBERSHIP_PAYMENT',
  COUPON_PURCHASE = 'COUPON_PURCHASE',
  TERMINAL_CASHBACK_CLAIM = 'TERMINAL_CASHBACK_CLAIM',
}
