import { ApiProperty } from "@nestjs/swagger";
import { IsNotEmpty, IsString, Length, IsUUID } from "class-validator";

export class ClaimCodeDto {
  @ApiProperty({
    description: "The 9-character unique code generated by staff/business",
  })
  @IsString()
  @Length(9, 9)
  @IsNotEmpty()
  code: string;

  @ApiProperty({ description: "The ID of the campaign" })
  @IsUUID()
  @IsNotEmpty()
  campaignId: string;
}
