'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { PlaquePreview } from '@/components/plaque/PlaquePreview';
import { ArrowLeft, Save, Printer } from 'lucide-react';
import Link from 'next/link';
import { toast } from 'sonner';
import { useCreateQrPlaque } from '@/services/qr-plaques/hook';

export default function CreatePlaquePage() {
    const router = useRouter();
    const { mutate: createPlaque, isPending } = useCreateQrPlaque();

    const [name, setName] = useState('');
    const [actionText, setActionText] = useState('SCAN HERE');
    const [description, setDescription] = useState('FOR PAYMENT');
    const [footerText, setFooterText] = useState('Powered by Mcom');
    const [contentUrl, setContentUrl] = useState('');

    // Using a placeholder for preview since actual QR is generated by backend
    const previewQrCodeUrl = '';

    const handleSave = () => {
        if (!name) {
            toast.error("Please provide a name for your plaque.");
            return;
        }

        createPlaque({
            name,
            actionText,
            description,
            footerText,
            contentUrl
        }, {
            onSuccess: () => {
                router.push('/dashboard/my-assets/qr-plaques');
            }
        });
    };

    const handlePrint = () => {
        window.print();
    };

    return (
        <div className="space-y-6">
             {/* Print Styles */}
            <style jsx global>{`
                @media print {
                    body * {
                        visibility: hidden;
                    }
                    #plaque-preview-container, #plaque-preview-container * {
                        visibility: visible;
                    }
                    #plaque-preview-container {
                        position: absolute;
                        left: 0;
                        top: 0;
                        width: 100%;
                        height: 100%;
                        display: flex;
                        justify-content: center;
                        align-items: center;
                        background: white;
                    }
                }
            `}</style>

            <div className="flex items-center gap-4">
                <Button variant="ghost" size="icon" asChild>
                    <Link href="/dashboard/my-assets/qr-plaques">
                        <ArrowLeft className="h-5 w-5" />
                    </Link>
                </Button>
                <div>
                    <h1 className="text-2xl font-bold tracking-tight">Create QR Plaque</h1>
                    <p className="text-muted-foreground">Design your custom plaque template.</p>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                {/* Editor Form */}
                <Card>
                    <CardHeader>
                        <CardTitle>Details</CardTitle>
                        <CardDescription>Enter the information to display on your plaque.</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4">
                        {/* 1. Name */}
                        <div className="space-y-2">
                            <Label htmlFor="plaqueName">Name of the QR Plaque <span className="text-red-500">*</span></Label>
                            <Input
                                id="plaqueName"
                                placeholder="e.g. Front Desk Display"
                                value={name}
                                onChange={(e) => setName(e.target.value)}
                            />
                        </div>

                        {/* 2. Description */}
                        <div className="space-y-2">
                            <Label htmlFor="description">Description</Label>
                            <Input
                                id="description"
                                placeholder="FOR PAYMENT"
                                value={description}
                                onChange={(e) => setDescription(e.target.value)}
                            />
                        </div>

                        {/* 3. Action Text */}
                        <div className="space-y-2">
                            <Label htmlFor="actionText">Action Text</Label>
                            <Input
                                id="actionText"
                                placeholder="Scan here or Scan now"
                                value={actionText}
                                onChange={(e) => setActionText(e.target.value)}
                            />
                        </div>

                        {/* 4. Content URL (Linked Offer) */}
                        <div className="space-y-2">
                            <Label htmlFor="contentUrl">Content URL / Linked Offer</Label>
                            <Input
                                id="contentUrl"
                                placeholder="https://mcomloyalty.com/..."
                                value={contentUrl}
                                onChange={(e) => setContentUrl(e.target.value)}
                            />
                        </div>

                        {/* 5. Footer (Footer Text) */}
                        <div className="space-y-2">
                            <Label htmlFor="footerText">Footer Text</Label>
                            <Input
                                id="footerText"
                                placeholder="e.g. Powered by Mcom"
                                value={footerText}
                                onChange={(e) => setFooterText(e.target.value)}
                            />
                        </div>

                        <div className="pt-4 flex gap-4">
                            <Button onClick={handleSave} className="flex-1" disabled={isPending}>
                                <Save className="mr-2 h-4 w-4" />
                                {isPending ? 'Saving...' : 'Save Template'}
                            </Button>
                        </div>
                    </CardContent>
                </Card>

                {/* Live Preview */}
                <div className="flex flex-col gap-4">
                    <div className="flex items-center justify-between">
                        <h2 className="text-lg font-semibold">Live Preview</h2>
                         <Button variant="outline" size="sm" onClick={handlePrint}>
                            <Printer className="mr-2 h-4 w-4" /> Print / PDF
                        </Button>
                    </div>

                    <div className="border rounded-lg p-8 bg-gray-50 flex items-center justify-center min-h-[500px]">
                        <div id="plaque-preview-container">
                            <PlaquePreview
                                title={name}
                                actionText={actionText}
                                description={description}
                                extraInfo={footerText}
                                qrCodeUrl={previewQrCodeUrl}
                            />
                            <p className="text-xs text-gray-400 mt-2 text-center">QR Code will be generated upon saving.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
