export enum DealType {
  DISCOUNT = "DISCOUNT",
  BUNDLE = "BUNDLE",
  BOGO = "BOGO",
  FLASH_SALE = "FLASH_SALE",
  GIFT_CARD = "GIFT_CARD",
  SERVICE_PACKAGE = "SERVICE_PACKAGE",
  INTRO_OFFER = "INTRO_OFFER",
  SEASONAL = "SEASONAL",
  EARLY_BIRD = "EARLY_BIRD",
  REFERRAL_DEAL = "REFERRAL_DEAL",
}
