export enum ImageSourceType {
  BUSINESS_LOGO = "BUSINESS_LOGO",
  SECTOR_LOGO = "SECTOR_LOGO",
  CATEGORY_LOGO = "CATEGORY_LOGO",
  SUB_CATEGORY_LOGO = "SUB_CATEGORY_LOGO",
  LIBRARY_ASSET = "LIBRARY_ASSET",
  EMOJI = "EMOJI",
  CUSTOM_URL = "CUSTOM_URL",
}
